image: gradle:alpine

default:
  tags:
    - shelllocal

stages:
  - test

Integration tests with Allure:
  stage: test
  script:
    - ./gradlew clean test
  after_script:
    - ./gradlew allure-results
  artifacts:
    when: always
    paths:
      - build/allure-results/*