# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflowg will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - uses: allure-framework/setup-allurectl@v1
      with:
        allure-endpoint: https://autotestreadtheory.testops.cloud
        allure-token: ${{ secrets.ALLURE_TOKEN }}
        allure-project-id: 1
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
    - run: allurectl watch -- ./gradlew clean test
      env:
        ALLURE_RESULTS: app/build/allure-results

